### ISSUE TITLE
Question regarding the file named "start"

### ISSUE THREAD

**Issue by zareone** [paulczar/docker-mysql#2]
I just wanted to know where the start file is used from, since the Dockerfile does not ADD it to the container, and I don't see any references to it.

https://github.com/paulczar/docker-mysql/blob/master/start

What am I missing?

Thanks in advance!

**Comment by paulczar** [comment]
hey buddy,   I think the start file is just an artifact from some testing.    can safely ignore it.  I'll delete it from the repo to avoid confusion after I double check.

**Comment by zareone** [comment]
Hi Paul! 
Thanks for the reply. I started using Docker two days ago, and I'm still a bit lost with it. 
I thought it could be some non-documented feature for the Docker builder.

Cheers!
